### ISSUE TITLE
Records showing up on records tab without division tag after deleting the division

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#3731]
**Describe the bug in current situation**
When a ministry division is deleted then the corresponding records are showing up on the records tab without division tag

**Link bug to the User Story**

**Impact of this bug**
It shows the deleted divisions records on records tab without division tag and shows corrupted file folder when downloading harms

**Chance of Occurring (high/medium/low/very low)**

High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test -marshal

**Steps to Reproduce**
1. Go to Ministry login
2. Go to any request and add some divisions
3. Upload some records for each division on records tab
4. Then come back to request and delete one division 
5. Then come back to records tab and deleted division's records are still visible without division tag
6.Also when download the harms, corrupted folder is created at the user end

**Actual/ observed behaviour/ results**

**Expected behaviour**
**Needs to block the deleting ability if a record is uploaded for that corresponding division on the records tab**

**Screenshots/ Visual Reference/ Source**

If applicable, add screenshots to help explain your problem. You an use screengrab.

Records tab before deletion
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/b18074c6-1605-4e58-acf3-1c9f35c3a03c)

Records tab for all divisions  after deleting division 'Deputy Minister's office '

![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/84bf60b0-65bc-4e55-951f-7a9ad06086a0)

Records tab for division 'Deputy Minister's Office' after it is been deleted from request
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/5b8c90a7-1213-4a10-892d-84864b2b9a44)

When download the harms, it shows a folder without name

![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/9774c82f-c9f4-4143-9477-56aa2121b21e)

**Comment by nimya-aot** [comment]
@JHarrietha-AOT Please review the ticket.

**Comment by JHarrietha-AOT** [comment]
@nimya-aot I touched base with Matt and Lise on Friday. So how we would want to fix this bug is as follows.

- We would like for a module to appear when a user try's to delete a Ministries - this will only happen if user has assigned a divisional state, due date or other details, but NOT upload any records. It ask the user if they are sure they would like to delete the division as all data will be lost.

- A different module will also appear if they have uploaded records but it will not allow them to delete the division, and will instruct the user if they would like to delete the division they must first delete all records that have been upload for this division to preserve the Records Package. 

- An additional thing Matt and Lise though of is that fact that divisions change names, so we want to ensure we preserve all records in the situation that the divisons name has been changed. 

I will link the designs for these module before end of day, let me know if you have any questions

**Comment by sumathi-thirumani-aot** [comment]
Fixed. Changes made to look up division from master data.

**Comment by JHarrietha-AOT** [comment]
@liseandtea @m-prodan Here is what I came up with for the modules, let me know if you would like me to change the text. And I can change it when I get back later tonight

https://jacklyn808742.invisionapp.com/overview/Redaction-cla8feezv003o015h7op82c5c/screens
https://jacklyn808742.invisionapp.com/overview/Redaction-cla8feezv003o015h7op82c5c/screens

**Comment by nimya-aot** [comment]
@sumathi-thirumani-aot One issue related to this, when we update a division name after uploading records corresponding to that division and try to download the harms it still shows the old division name as folder name

**Comment by KyEggleston** [comment]
Notes from standup - users should not be able to delete or change a division in divisional tracking when there are records in the gathering records log tagged with that division. 

Do we need a modal for when users attempt to change a division when there are records in the Gathering Records log tagged with the division? (e.g., similar to the "cannot delete this division" modal)? @JHarrietha-AOT

**Comment by sumathi-thirumani-aot** [comment]
@JHarrietha-AOT In the UX, I believe we don't need the delete button itself. Because it will not show up if no records are associated and it is only an information message. Can you please have a look.

**Comment by sumathi-thirumani-aot** [comment]
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/de3f1cfb-caa0-4faf-a123-e84b043e84a4)

**Comment by sumathi-thirumani-aot** [comment]
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/6d104774-0562-43ec-8aac-bf8988afead9)


![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/5c79fa99-c8c8-4bb0-a9a3-80df39e14fa7)

**Comment by sumathi-thirumani-aot** [comment]
@JHarrietha-AOT Please let me know which option to go with.

**Comment by JHarrietha-AOT** [comment]
@m-prodan @liseandtea What do you both think of just removing the delete button? It makes sense to me and as apart of training we can train this piece that you can't delete a division that has records associated with it. If it does not have any records associated with it then you get a module to ensure they don't accidentally delete it.

**Comment by JHarrietha-AOT** [comment]
That's exactly what I am thinking @liseandtea so the delete button would disappear when records have been uploaded that are associated with the division. If there are no records then the delete would appear and the user would get the module ensure they wish to delete a division.

@sumathi-thirumani-aot what do you think of this solution?

**Comment by JHarrietha-AOT** [comment]
@sumathi-thirumani-aot just making a note here we will switch it to one button that says okay.

For the wording my only change would be prior should have a lowecase p. and there should be a period at the end of the bottom sentence

**Comment by nimya-aot** [comment]
working as expected
