### ISSUE TITLE
Redact Pages - Multiple Bugs 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4398]
**Describe the bug in current situation**
When using the 'Redact Pages' feature, several bugs occur through it's initial use, and when it is subsequently used. See steps to reproduce. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

Test Marshal 
EDU-2023-99920

**Steps to Reproduce**
1. Go to a request with multiple pages in the redaction app 
2. Select 'Redact Pages', and under 'Specify Pages', select two or more pages (in my example, I did Page 1, 2-6), and click 'Add Mark'
3. Add a FOIPPA section(s), and click 'Select 'Code(s)'
4. Review the pages that have been flagged and see error where the FOIPPA section is sometimes duplicated (this is documented in #4378)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHQ4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--972e35214b0c3ae8e22039a84cf2e5c5abb9dd94/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHg4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1f9f06b129485d5b5366a3c516cdb4cf9a9653e3/image.png)

6. Next, bulk delete all your redactions you applied. 
7. The redactions will be deleted, but not that not all the page flags will be removed. (In the image below, the Page 5 flag remained, but there are not redactions on the page, and in the Comments tab all redactions were deleted)

![image](https://github.com/bcgov/foi-flow/assets/117312323/ef39a9e7-73ab-4bce-b2fe-59b840b76bb1)

8. Next, try to add new pages to redact in full under 'Redact Pages' (in my example, I did Page 8, 10-12)

![image](https://github.com/bcgov/foi-flow/assets/117312323/62300269-7a46-4585-a7bd-0d2c982f8a9e)

9. After, see the error, where all the previous pages that were redacted using 'Redact Pages' are reflagged. However, only the new full pages you selected to redact (e.g., pages 8, 10-12) have a redaction applied, as seen in the 'Comments' tab. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/c2f21517-16eb-4d0e-a52c-da384f1799d3)

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
cc: @lmullane @m-prodan @JHarrietha-AOT - lots of issues with redact pages. Perhaps if one of you have time tomorrow, you can go through this feature and the steps above and further refine this ticket.

**Comment by KyEggleston** [comment]
Part of this is documented in #4378

**Comment by m-prodan** [comment]
Believe the double stamp has been fixed in #4385 - check against both find and redact and full page redactions.

@nkan-aot may have fixed page flag issue and remembering redactions, but needs to confirm (not yet in test)

**Comment by lmullane** [comment]
Deleting bulk redactions still does not seem to remove all the Page Flags.

**Comment by nimya-aot** [comment]
working as expected, so closing
