### ISSUE TITLE
Redline PDF cannot be created

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#4557]
**Describe the bug in current situation**

A request has 100% of pages flagged and is in a state (Peer Review) that a Redline should be able to be produced.

But the redline PDF is greyed out on the dropdown.

**Link bug to the User Story**
#3437

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

High. Does not appear to be a work around.

**Chance of Occurring (high/medium/low/very low)**
Low-to-medium. Analysts should wait until request is in Records Review before trying to produce a Redline PDF

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a request
2. Keep the request state in Call for Records
3. Flag all pages in the records package until at 100%
4. Click on Create Redline - inactive
5. Update state to Peer Review
6. See that the Redline for Sign Off is still inactive

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language

Scenario 5: Active 'Redline for Sign Off'
From story #3437

GIVEN a records package is in Records Review, Ministry Sign Off or Peer Review
AND every page in the Records Package has one of these page flags applied: Partial Disclosure, Full Disclosure, Withheld in Full, Duplicate, Not Responsive
WHEN the IAO analyst clicks on the "Create Records Package" dropdown
THEN the "Redline for Sign Off" will be clickable
AND the "Response Package for Applicant" will not be clickable

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjcvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bcba9cf64323a6f3658a0de5187a511b7654d3f7/Screenshot%202023-10-03%20at%201.44.53%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0gvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--18c762527c9078df3aa7d8c4e8e13734b4306d44/Screenshot%202023-10-03%20at%201.45.17%20PM.png)

**Comment by lmullane** [comment]
@m-prodan, possible bug on the order of operations (i.e., possibly due to finishing page flags before the request is in a proper state).

Will see if we can reproduce.

**Comment by lmullane** [comment]
I was able to reproduce this bug with another TEST request. 

I also found uploading a new record to the Records Log when the request was in the correct state (e.g., Records Review) allowed a redline to be created, provided all pages were appropriately flagged.

**Comment by milosdes** [comment]
I was finally able to reproduce this bug with a bit of assistance from @aparna-aot . I think it might have something to do with the order/speed with which files are loaded, especially when a request has a lot of files. 
If you go to the [request](https://test-reviewer-web-marshal.apps.silver.devops.gov.bc.ca/foi/669) from the screenshot here and refresh it, sometimes the button will be greyed out and sometimes it won't.

This is likely from the Redlining.js component running the ``` checkSavingRedlineButton() ``` function before all the files are loaded, and then not running it again after. 

Will try a fix tomorrow by calling the function again after documents are all loaded.

**Comment by milosdes** [comment]
This fix was merged to test-marshal in commit c38ce5149f01ac72f8ee88393c36f4fbcef9875b

**Comment by nimya-aot** [comment]
@milosdes this issue is still exists. First time when it loads, 'Redline for sign off' button is still grey out. Could you please check?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelFnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7e89a3a444a3338b32f3864afc33854ba0f8f4d/image.png)

**Comment by milosdes** [comment]
Yes I saw that, thanks @nimya-aot. It looks like I put the fix in the wrong place in the code. Will have this back up by end of day hopefully.

**Comment by milosdes** [comment]
@nimya-aot I updated this and tested it, the original bug seems to be gone now.

**Comment by nimya-aot** [comment]
working as expected so closing it
